version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Istanbul
      # Webhook'ların dışarıdan erişilebilir olması için
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      # JSON ve YAML işleme için gerekli kütüphaneleri etkinleştir
      - NODE_FUNCTION_ALLOW_EXTERNAL=js-yaml,yaml,fs-extra
    volumes:
      - ./n8n_data:/home/node/.n8n
      # Konfigürasyon dosyaları
      - ./configs:/mnt/workflow_configs
      # Kurallar için ayrı bir klasör (opsiyonel)
      - ./configs/kurallar:/configs/kurallar
      # Veri Kaynağı Eşleştirmeleri (proje dizininden relative path):
      - ./veri_kaynaklari:/mnt/workflow_data
    # user: "1000:1000" # Uncomment if you have permission issues

volumes:
  n8n_data: # Define the volume if not using local path mapping above
