version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Istanbul
      # Webhook'ların dışarıdan erişilebilir olması için
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      # JSON ve YAML işleme için gerekli kütüphaneleri etkinleştir
      - NODE_FUNCTION_ALLOW_EXTERNAL=yaml,fs-extra
    volumes:
      - ./n8n_data:/home/node/.n8n
      # Veri kaynaklarını tek bir ana klasör altında organize et
      - ./synthetic_data:/veri_kaynaklari/hastane
      - ./synthetic_data_cagri_merkezi:/veri_kaynaklari/cagri_merkezi
      # Konfigürasyon dosyaları
      - ./configs:/configs
      # Kurallar için ayrı bir klasör (opsiyonel)
      - ./configs/kurallar:/configs/kurallar

volumes:
  n8n_data: # Define the volume if not using local path mapping above
