institution_id: "112_cagri_merkezi_bolge_x"
institution_name: "Bölge X - 112 Acil Çağrı Merkezi"
problem_type: "shift_scheduling"

optimization_core:
  solver_time_limit_seconds: 120
  objective_weights:
    minimize_overstaffing: 1.5
    minimize_understaffing: 100
    maximize_preferences: 1
    balance_workload: 3.0
    maximize_shift_coverage: 50

rules:
  min_staffing_requirements:
    # Sabah vardiyaları için Çağrı Alıcı gereksinimleri - Daha genel desen
    - shift_pattern: "*Genel Çağrı*"
      role: "Çağrı Alıcı"
      department: "Genel Çağrı"
      min_count: 1  # 4'ten 1'e düşürüldü - Test amaçlı daha da gevşetme
      penalty_if_violated: 200

    # Gece hafta sonu vardiyaları için Çağrı Alıcı gereksinimleri - Kaldırıldı (genel desen yeterli)

    # Polis Yönlendirme departmanı için Yönlendirici gereksinimleri
    - shift_pattern: "*"
      role: "Yönlendirici"
      department: "Polis Yönlendirme"
      min_count: 1  # 2'den 1'e düşürüldü
      penalty_if_violated: 300

    # İtfaiye Yönlendirme departmanı için Yönlendirici gereksinimleri
    - shift_pattern: "*"
      role: "Yönlendirici"
      department: "İtfaiye Yönlendirme"
      min_count: 1  # Aynı kaldı
      penalty_if_violated: 300

    # Sağlık Yönlendirme departmanı için Yönlendirici gereksinimleri
    - shift_pattern: "*"
      role: "Yönlendirici"
      department: "Sağlık Yönlendirme"
      min_count: 1  # 2'den 1'e düşürüldü
      penalty_if_violated: 300

    # Tüm vardiyalar için Vardiya Amiri gereksinimleri
    - shift_pattern: "*"
      role: "Vardiya Amiri"
      department: "Yönetim"
      min_count: 1
      penalty_if_violated: 500

  max_consecutive_shifts: 7  # 5'ten 7'ye artırıldı - Çok daha esnek çalışma düzeni
  min_rest_time_hours: 1   # 6'dan 1'e düşürüldü - Çözümsüzlüğü test etmek için aşırı gevşetme

  skill_requirements:
    # Polis Yönlendirme departmanı için yetenek gereksinimleri
    - shift_pattern: "*"
      skill: "Polis Kriz Protokolleri"
      department: "Polis Yönlendirme"
      role: "Yönlendirici"
      min_count: 1
      penalty_if_violated: 150

    # Genel Çağrı departmanı için yetenek gereksinimleri
    - shift_pattern: "*"
      skill: "İleri Düzey Stres Yönetimi"
      department: "Genel Çağrı"
      role: "Çağrı Alıcı"
      min_count: 1  # 2'den 1'e düşürüldü
      penalty_if_violated: 100

    # Sağlık Yönlendirme departmanı için yetenek gereksinimleri
    - shift_pattern: "*"
      skill: "Temel Tıbbi Triyaj Bilgisi"
      department: "Sağlık Yönlendirme"
      role: "Yönlendirici"
      min_count: 1
      penalty_if_violated: 180

    # Yönetim departmanı için yetenek gereksinimleri
    - shift_pattern: "*"
      skill: "Liderlik ve Koordinasyon"
      department: "Yönetim"
      role: "Vardiya Amiri"
      min_count: 1
      penalty_if_violated: 200

n8n_parameters:
  notification_emails:
    - "112koordinator@bolgex.gov.tr"
  report_template: "cagri_merkezi_standart_rapor.tpl"