institution_id: "cagri_merkezi_config"

institution_name: "Test Çağrı Merkezi"

problem_type: "shift_scheduling"

optimization_core:
  solver_time_limit_seconds: 60
  objective_weights:
    minimize_overstaffing: 1
    minimize_understaffing: 10
    maximize_preferences: 2
    balance_workload: 0.5
    maximize_shift_coverage: 1

rules:
  min_staffing_requirements:
    # Müşteri Hizmetleri Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Temsilci"
      department: "Müşteri Hizmetleri"
      min_count: 2
      penalty_if_violated: 100
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Temsilci"
      department: "Müşteri Hizmetleri"
      min_count: 1
      penalty_if_violated: 150
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Temsilci"
      department: "Müşteri Hizmetleri"
      min_count: 1
      penalty_if_violated: 80

    # Teknik Destek Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Uzman Temsilci"
      department: "Teknik Destek"
      min_count: 1
      penalty_if_violated: 120
    - shift_pattern: "*Mesai*Hafta*İçi*"
      role: "Temsilci"
      department: "Teknik Destek"
      min_count: 1
      penalty_if_violated: 100

    # Satış Departmanı Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Uzman Temsilci"
      department: "Satış"
      min_count: 1
      penalty_if_violated: 90

    # Yönetim Gözetimi
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Süpervizör"
      department: "Yönetim"
      min_count: 1
      penalty_if_violated: 200

  max_consecutive_shifts: 3
  min_rest_time_hours: 10

  # Yetenek/Sertifika Gereksinimleri
  skill_requirements:
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      skill: "Çoklu Dil"
      department: "Müşteri Hizmetleri"
      min_count: 1
      penalty_if_violated: 80
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      skill: "Teknik Bilgi"
      department: "Teknik Destek"
      min_count: 1
      penalty_if_violated: 100
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      skill: "Satış Deneyimi"
      department: "Satış"
      min_count: 1
      penalty_if_violated: 70



