institution_id: "hospital_test"
institution_name: "Test Hastanesi"
problem_type: "shift_scheduling"

# Optimizasyon Çekirdeği Parametreleri
optimization_core:
  solver_time_limit_seconds: 60
  # Önceliklendirme için hedef fonksiyonu ağırlıkları
  objective_weights:
    minimize_overstaffing: 1
    minimize_understaffing: 10  # Eksik personelin cezası daha yüksek
    maximize_preferences: 2

# Modele Eklenecek Dinamik Kısıtlar ve Kurallar
rules:
  min_staffing_requirements:
    - shift_pattern: "Gece*"  # Gece ile başlayan tüm vardiyalar
      role: "Hemşire"
      min_count: 2
    - shift_pattern: "Gündüz*"
      role: "Doktor"
      min_count: 1

  max_consecutive_shifts: 3
  min_rest_time_hours: 10

  # Yetenek/Sertifika Gereksinimleri
  skill_requirements:
    - shift_pattern: "*Hafta Sonu*"  # Hafta sonu vardiyaları
      skill: "Acil Servis Deneyimi"
      min_count: 1

# n8n Parametreleri
n8n_parameters:
  notification_emails:
    - "test@testhastanesi.com"
  report_template: "hospital_report.tpl"
