institution_id: "hospital_test"
institution_name: "Test Hastanesi"
problem_type: "shift_scheduling"

# Optimizasyon Çekirdeği Parametreleri
optimization_core:
  solver_time_limit_seconds: 60
  # Önceliklendirme için hedef fonksiyonu ağırlıkları
  objective_weights:
    minimize_overstaffing: 1
    minimize_understaffing: 10  # Eksik personelin cezası daha yüksek
    maximize_preferences: 2
    balance_workload: 0.5       # İş yükünü eşit dağıtma (yeni)
    maximize_shift_coverage: 1  # Vardiya doluluğunu maksimize etme (yeni)

# Modele Eklenecek Dinamik Kısıtlar ve Kurallar
rules:
  min_staffing_requirements:
    # Acil Servis Gereksinimleri - Joker karakterli desenler
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Hemşire"
      department: "Acil"
      min_count: 1  # 2'den 1'e düşürüldü
      penalty_if_violated: 100  # Yumuşak kısıt eklendi
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Acil"
      min_count: 1
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Doktor"
      department: "Acil"
      min_count: 1

    # Yoğun Bakım Gereksinimleri - Joker karakterli desenler
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Hemşire"
      department: "Yoğun Bakım"
      min_count: 2
      penalty_if_violated: 100  # Yumuşak kısıt eklendi
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Yoğun Bakım"
      min_count: 1
      penalty_if_violated: 100  # Yumuşak kısıt eklendi

    # Kardiyoloji Gereksinimleri - Joker karakterli desenler
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Kardiyoloji"
      min_count: 1
      penalty_if_violated: 100  # Yumuşak kısıt eklendi

    # Pediatri Gereksinimleri - Joker karakterli desenler
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Hemşire"
      department: "Pediatri"
      min_count: 1
      penalty_if_violated: 100  # Yumuşak kısıt eklendi
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Hemşire"
      department: "Pediatri"
      min_count: 1
      penalty_if_violated: 100  # Yumuşak kısıt eklendi

  max_consecutive_shifts: 3
  min_rest_time_hours: 10

  # Yetenek/Sertifika Gereksinimleri - Joker karakterli desenler
  skill_requirements:
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      skill: "Acil Servis Deneyimi"
      department: "Acil"
      min_count: 1
    - shift_pattern: "*Gece*Hafta*İçi*"
      skill: "Yoğun Bakım Sertifikası"
      department: "Yoğun Bakım"
      min_count: 1
      penalty_if_violated: 100  # Yumuşak kısıt eklendi

# n8n Parametreleri
n8n_parameters:
  notification_emails:
    - "test@testhastanesi.com"
  report_template: "hospital_report.tpl"
