institution_id: "optimized_hospital_test"
institution_name: "Optimized Test Hastanesi"
problem_type: "shift_scheduling"

# Optimizasyon Çekirdeği Parametreleri - Dengeli Ağırlıklar
optimization_core:
  solver_time_limit_seconds: 60
  # Balanced Multi-Objective - Gerçek çok amaçlı optimizasyon için dengeli ağırlıklar
  objective_weights:
    minimize_understaffing: 10      # Hasta güvenliği için en yüksek öncelik
    maximize_shift_coverage: 5      # Operasyonel süreklilik
    maximize_preferences: 4         # Çalışan memnuniyeti, makul seviye
    minimize_overstaffing: 3        # Maliyet kontrolü
    balance_workload: 2             # Uzun vadeli sürdürülebilirlik

# Modele Eklenecek Dinamik Kısıtlar ve Kurallar
rules:
  min_staffing_requirements:
    # Acil Servis Gereksinimleri
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Hemşire"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50  # Azaltıldı (100 → 50)
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Doktor"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50

    # Yoğun Bakım Gereksinimleri
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Hemşire"
      department: "Yoğun Bakım"
      min_count: 2
      penalty_if_violated: 50
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Yoğun Bakım"
      min_count: 1
      penalty_if_violated: 50

    # Kardiyoloji Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Kardiyoloji"
      min_count: 1
      penalty_if_violated: 50

    # Pediatri Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Hemşire"
      department: "Pediatri"
      min_count: 1
      penalty_if_violated: 50
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Hemşire"
      department: "Pediatri"
      min_count: 1
      penalty_if_violated: 50

  max_consecutive_shifts: 3
  min_rest_time_hours: 10

  # Yetenek/Sertifika Gereksinimleri
  skill_requirements:
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      skill: "Acil Servis Deneyimi"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50
    - shift_pattern: "*Gece*Hafta*İçi*"
      skill: "Yoğun Bakım Sertifikası"
      department: "Yoğun Bakım"
      min_count: 1
      penalty_if_violated: 50

# n8n Parametreleri
n8n_parameters:
  notification_emails:
    - "test@optimizedhastane.com"
  report_template: "optimized_hospital_report.tpl"
