institution_id: "optimized_hospital_test"
institution_name: "Optimized Test Hastanesi"
problem_type: "shift_scheduling"

# Optimizasyon Çekirdeği Parametreleri - İyileştirilmiş Ağırlıklar
optimization_core:
  solver_time_limit_seconds: 60
  # Preference Focused - En iyi performans için optimize edilmiş ağırlıklar
  objective_weights:
    minimize_overstaffing: 2        # Preference Focused (1 → 2)
    minimize_understaffing: 6       # Azaltıldı (10 → 6)
    maximize_preferences: 8         # Maksimum artırıldı (2 → 8)
    balance_workload: 3             # Artırıldı (0.5 → 3)
    maximize_shift_coverage: 2      # Artırıldı (1 → 2)

# Modele Eklenecek Dinamik Kısıtlar ve Kurallar
rules:
  min_staffing_requirements:
    # Acil Servis Gereksinimleri
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Hemşire"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50  # Azaltıldı (100 → 50)
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Doktor"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50

    # Yoğun Bakım Gereksinimleri
    - shift_pattern: "*Gece*Hafta*İçi*"
      role: "Hemşire"
      department: "Yoğun Bakım"
      min_count: 2
      penalty_if_violated: 50
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Yoğun Bakım"
      min_count: 1
      penalty_if_violated: 50

    # Kardiyoloji Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Doktor"
      department: "Kardiyoloji"
      min_count: 1
      penalty_if_violated: 50

    # Pediatri Gereksinimleri
    - shift_pattern: "*Gündüz*Hafta*İçi*"
      role: "Hemşire"
      department: "Pediatri"
      min_count: 1
      penalty_if_violated: 50
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      role: "Hemşire"
      department: "Pediatri"
      min_count: 1
      penalty_if_violated: 50

  max_consecutive_shifts: 3
  min_rest_time_hours: 10

  # Yetenek/Sertifika Gereksinimleri
  skill_requirements:
    - shift_pattern: "*Gündüz*Hafta*Sonu*"
      skill: "Acil Servis Deneyimi"
      department: "Acil"
      min_count: 1
      penalty_if_violated: 50
    - shift_pattern: "*Gece*Hafta*İçi*"
      skill: "Yoğun Bakım Sertifikası"
      department: "Yoğun Bakım"
      min_count: 1
      penalty_if_violated: 50

# n8n Parametreleri
n8n_parameters:
  notification_emails:
    - "test@optimizedhastane.com"
  report_template: "optimized_hospital_report.tpl"
